fix code #1

diff --git a/u2tmpfs b/u2tmpfs
--- a/u2tmpfs
+++ b/u2tmpfs
@@ -146,55 +146,56 @@ is_login() {
 }
 
 check_memory() {
+	local custom_size=0
 	local max_mem=$(cat /proc/meminfo \
 		| grep -E "^MemTotal:" \
 		| grep -o -E "[0-9]{1,}")
 
 	# convert to kB
 	if echo "${TMPFS_SIZE}" | grep -o -E "^[0-9]{1,}M$" > /dev/null; then
-		CUSTOM_SIZE=$(($(echo "${TMPFS_SIZE}" \
+		custom_size=$(($(echo "${TMPFS_SIZE}" \
 			| grep -o -E "^[0-9]{1,}") * 1024))
 
 	elif echo "${TMPFS_SIZE}" | grep -o -E "^[0-9]{1,}G$" > /dev/null; then
-		CUSTOM_SIZE=$(($(echo "${TMPFS_SIZE}" \
+		custom_size=$(($(echo "${TMPFS_SIZE}" \
 			| grep -o -E "^[0-9]{1,}") * 1048576))
 
 	elif echo "${TMPFS_SIZE}" | grep -o -E "^[0-9]{1,}$" > /dev/null; then
-		CUSTOM_SIZE=$(echo "${TMPFS_SIZE}" \
+		custom_size=$(echo "${TMPFS_SIZE}" \
 			| grep -o -E "^[0-9]{1,}$")
 	else
 		# if param TMPFS_SIZE is't avalible
-		CUSTOM_SIZE=$((${max_mem}/2))
+		custom_size=$((${max_mem}/2))
 	fi
 
 	# you can use only half of installed RAM
-	if ! (( $((${max_mem}/2)) >= ${CUSTOM_SIZE} )); then
+	if ! (( $((${max_mem}/2)) >= ${custom_size} )); then
 		return 1
+	else
+		MEM_SIZE=${custom_size}
 	fi
 }
 
 get_mem_size() {
-	# return CUSTOM_SIZE var
+	# return MEM_SIZE var
 	check_memory || return 1
 }
 
 check_arch_size() {
-	# get real size of user data (bytes)
+	# get real size of user data
 	if [ -f "${ARCH_FILE}" ]; then
-		ARCH_SIZE=$(/bin/tar -tJv -f "${ARCH_FILE}" \
+		ARCH_SIZE=$(( $(/bin/tar -tJv -f "${ARCH_FILE}" \
 			| sed 's/ \+/ /g' \
 			| cut -f3 -d ' ' \
 			| sed '2,$s/^/+ /' \
-			| paste -sd ' ' \
-			| awk '{ byte = $1 /1024 ; print byte ;byte = $1 /1024/1024 }')
+			| paste -sd ' ') * 1024 ))
 	else
 		return 1
 	fi
 
-	# get CUSTOM_SIZE var
+	# get MEM_SIZE var
 	get_mem_size || return 1
-
-	if ! (( ${ARCH_SIZE} <= ${CUSTOM_SIZE} )); then
+	if ! (( ${ARCH_SIZE} <= ${MEM_SIZE} )); then
 		return 1
 	fi
 }
@@ -230,8 +231,8 @@ update_user_data() {
 			}
 		fi
 
-		get_mem_size # get CUSTOM_SIZE var
-		if (( ${USER_DIR_SIZE} <= ${CUSTOM_SIZE} )); then
+		get_mem_size # get MEM_SIZE var
+		if (( ${USER_DIR_SIZE} <= ${MEM_SIZE} )); then
 			make_backup "${ARCH_FILE}"
 			/bin/mv --force "${WORK_FILE_PATH}" "${ARCH_FILE}" || return 1
 
@@ -251,8 +252,8 @@ extract_user_data() {
 	# get original size of user data from *.count file
 	USER_DIR_SIZE=$(cat "${ARCH_FILE}.count")
 
-	get_mem_size # get CUSTOM_SIZE var
-	if (( ${USER_DIR_SIZE} <= ${CUSTOM_SIZE} )); then
+	get_mem_size # get MEM_SIZE var
+	if (( ${USER_DIR_SIZE} <= ${MEM_SIZE} )); then
 		/bin/tar -xJp --skip-old-files \
 				--absolute-names ${ex_params} \
 				-f "${ARCH_FILE}" \
@@ -320,8 +321,8 @@ check_args && for user_name in `echo "${USERS}" | tr "," "\n"`; do
 		} || {
 			wipe_workfile "${WORK_FILE_PATH}"
 			restore_backup "${ARCH_FILE}"
-			echo "Error while updating the USER_DATA..."
-			exit 1
+			echo "Error while updating the USER_DATA for ${user_name}..."
+			continue
 		}
 
 	# if ARCH_FILE is not found, you need update user data into...
