global update

diff --git a/u2tmpfs b/u2tmpfs
--- a/u2tmpfs
+++ b/u2tmpfs
@@ -1,29 +1,42 @@
 #!/usr/bin/env bash
 
+################################################
+## Defaults
+################################################
+# Blacklist users (by commas)
 BLACKLIST_USERS="root"
+
+# Where is save a user data (chmod 0740 USER_DATA_DIR)
 USER_DATA_DIR="/var/lib/u2tmpfs"
+
+# TMPFS size mount option (M — megabyte, G — gigabyte)
 TMPFS_SIZE="512M"
+
+# Other mount specified options (mount -o [..])
 MOUNT_OPTS="mode=755,noatime"
 
-UPDATE_STAT=0
-
-_SCR_NAME=`basename "$0"`
-
-if ! [ "` cat /proc/filesystems | grep -o -E "tmpfs$" | head -n1`" ]; then
+################################################
+## Body
+################################################
+if ! [ "`cat /proc/filesystems | grep -o -E "tmpfs$" | head -n1`" ]; then
 	echo "Error: kernel is not support a temporary filesystem (tmpfs)"
 	exit 1
 else
 	[ "$(/usr/bin/id -u)" != "0" ] && {
 		echo -e "You need a root priveleges\n"
-	#	exit
+#		exit 1
 	}
 fi
+
+UPDATE_STAT=0
+_SCR_NAME=`basename "$0"`
 
 print_help() {
 	cat << EOF
 Usage: ${_SCR_NAME} [-U] [-u USER1,USER2]
                [-d USER_DATA_DIR]
                [-s TMPFS_SIZE]
+               [-o MOUNT_OPTS]
 
 Simple script for automount home dir to tmpfs when your system is booting and extract all user data there. 
 
@@ -31,8 +44,8 @@ ${_SCR_NAME} parameters:
   -u       Enter users (separated by commas. Example: user1,user2,etc)
   -d       Directory for user data files (for *.tar.xz. Default: ${USER_DATA_DIR})
   -U       Create/Update all *.tar.xz
-  -s       tmpfs size option (mount -o) (Example: 512M, 4G. Default: 1G)
-  -m       Use the specified mount options for tmpfs (Default: "${MOUNT_OPTS}")
+  -s       tmpfs size option (mount -o size) (Example: 512M, 4G. Default: 512M)
+  -o       Use the specified mount options for tmpfs (Default: "${MOUNT_OPTS}")
 
 Example:
 	1) Only init/update all users data without "mount -t tmpfs ...":
@@ -44,6 +57,32 @@ Example:
 EOF
 	exit
 }
+
+## Parse args
+while [[ $# != 0 ]]; do
+	case "$1" in
+		-h ) print_help ;;
+
+		-u ) USERS="$2" ; shift ;;
+
+		-U ) UPDATE_STAT=1 ;;
+
+		-d ) USER_DATA_DIR="$2" ; shift ;;
+
+		-s ) TMPFS_SIZE="$2" ; shift ;;
+
+		-o )
+			echo "comming soon..."
+			print_help
+			;;
+
+		* )
+			echo "Unknown command: $1"
+			print_help
+			;;
+	esac
+	shift
+done
 
 check_args() {
 	if ! [[ -z "${@}" ]]; then
@@ -69,16 +108,42 @@ check_args() {
 	fi
 }
 
-update_user_data() {
-	local ex_params="$@"
-	[ -d "${USER_DATA_DIR}" ] || /bin/mkdir --mode=0740 -p ${USER_DATA_DIR}
+check_bl() {
+	local curr_user="$1"
 
+	for bl_user in `echo "${BLACKLIST_USERS}" | tr "," "\n"`; do
+		if [[ "${curr_user}" == "${bl_user}" ]] ; then
+			return 1
+		fi
+	done
+}
+
+get_meminfo() {
+	return
+}
+
+check_memory() {
+	if get_meminfo; then
+		return
+	else
+		return 1
+	fi
+}
+
+update_user_data() {
+	# custom args for /bin/tar
+	local ex_params="$@"
+
+	# get random string (6)
 	RAND_STRING=`cat /dev/urandom \
 					| tr -dc 'a-z0-9' \
 					| fold -w 6 \
 					| head -n 1`
 
+	# Temp file...
 	WORK_FILE_PATH="/tmp/${user_name}-${RAND_STRING}.tar.xz"
+
+	[ -d "${USER_DATA_DIR}" ] || /bin/mkdir --mode=0740 -p ${USER_DATA_DIR}
 	/bin/tar -cJp --absolute-names \
 				  -f "${WORK_FILE_PATH}" \
 				  --anchored ${ex_params} "${USER_DIR}" > /dev/null && {
@@ -91,7 +156,9 @@ update_user_data() {
 }
 
 extract_user_data() {
+	# custom args for /bin/tar
 	local ex_params="$@"
+
 	/bin/tar -xJp --absolute-names ${ex_params} \
 				  -f "${ARCH_FILE}" \
 				  -C "${USER_DIR}" > /dev/null || return 1
@@ -104,56 +171,25 @@ mount_tmpfs() {
 	local size="$4"
 
 	if mount | grep -E "^tmpfs" | grep ${udir} > /dev/null; then
+		# skip mounting
 		return
 	else
 		/bin/mount -o size=${size},uid=${uid},gid=${ugid},${MOUNT_OPTS} \
-				   -t tmpfs tmpfs "${udir}" > /dev/null && {
-			return
-		} || {
-			echo "Error mount file to ${udir}"
+				   -t tmpfs tmpfs "${udir}" > /dev/null || {
 			return 1
 		}
 	fi
 }
 
-# parse args
-while [[ $# != 0 ]]; do
-	case "$1" in
-		-h )
-			print_help
-			;;
+## Check args, get USERS and tune HOME dir...
+check_args && for user_name in `echo "${USERS}" | tr "," "\n"`; do
 
-		-u )
-			USERS="$2" ; shift
-			;;
+	# required parameters
+	if ! [ "`cat /etc/passwd | grep -E "^${user_name}"`" ]; then
+		echo "User \"${user_name}\" is not found in your system!"
+		continue
+	fi
 
-		-U )
-			UPDATE_STAT=1
-			;;
-
-		-d )
-			USER_DATA_DIR="$2" ; shift
-			;;
-
-		-s )
-			TMPFS_SIZE="$2" ; shift
-			;;
-
-		-m )
-			echo "comming soon..."
-			;;
-
-		* )
-			echo "Unknown command: $1"
-			print_help
-			;;
-	esac
-	shift
-done
-
-check_args && for user_name in `echo ${USERS} | tr "," "\n"`; do
-
-	ARCH_FILE="${USER_DATA_DIR}/${user_name}.tar.xz"
 	C_USER=$(cat /etc/passwd \
 				| grep -E "^${user_name}" \
 				| cut -d ":" -f 3)
@@ -163,39 +199,43 @@ check_args && for user_name in `echo ${USERS} | tr "," "\n"`; do
 	USER_DIR=$(cat /etc/passwd \
 				| grep -E "^${user_name}" \
 				| cut -d ":" -f 6)
-
-	for bl_users in `echo ${BLACKLIST_USERS} | tr "," "\n"`; do
-		if [[ "${user_name}" == "${bl_users}" ]] ; then
-			echo "This user is not allowed: ${user_name}"
-			exit 1
-		fi
-	done
-
-	if ! [ "`cat /etc/passwd | grep -E "^${user_name}"`" ]; then
-		echo "User \"${user_name}\" is not found in your system!"
-		continue
-	fi
+	ARCH_FILE="${USER_DATA_DIR}/${user_name}.tar.xz"
 
 	if ! [ -d "${USER_DIR}" ]; then
 		echo "\"${USER_DIR}\" — for ${user_name} is not found!"
 		exit 1
-	fi
 
-	if [ ${UPDATE_STAT} -eq 1 ]; then
-		update_user_data
+	elif ! check_bl "${user_name}"; then
+		echo "\"${user_name}\" — is not allowed!"
+
+		# skip this user
 		continue
+
+	elif [ ${UPDATE_STAT} -eq 1 ]; then
+		update_user_data && {
+			# after update skip mount and extract user data...
+			continue
+		} || {
+			echo "Error while updating the USER_DATA..."
+			exit 1
+		}
 	fi
 
+	# if ARCH_FILE is not found, you need update user data into...
 	if ! [ -f "${ARCH_FILE}" ]; then
 		echo "You need update user data files (${_SCR_NAME} -U -u user1,user2)"
 		print_help
 		exit 1
 	fi
 
+	# Mount TMPFS to HOME dir (for this "user_name") and extract user data from ARCH_FILE
 	mount_tmpfs ${USER_DIR} ${C_USER} ${C_GROUP} ${TMPFS_SIZE} && {
-		extract_user_data || exit 1
+		extract_user_data || {
+			echo "Error while unpacking the USER_DATA..."
+			exit 1
+		} 
 	} || {
-		echo "Error whith mounting..."
+		echo "Error during mounting HOME dir (${USER_DIR}) to TMPFS"
 		exit 1
 	}
 
